### ISSUE TITLE
LFS data quota exceeded

### ISSUE THREAD

**Issue by playdasegunda** [kuielab/sdx23#1]
Hello,

I am trying to clone the repository but I am receiving an error indicating that the LFS data quota has been exceeded. Here is the error message I received:

```
Error downloading object: my_submission/ckpts/modelA/step100000_seed0.ckpt (ec3ab4a): Smudge error: Error downloading my_submission/ckpts/modelA/step100000_seed0.ckpt (ec3ab4a8327d6db696d9ae51c5a38573186461182007d0dd9a09ad662a5ef1ae): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

Could you please check this and let us know how we can resolve this issue? One suggestion could be to upload the checkpoints to another hosting service, such as Google Drive.

Thank you.

**Comment by rlaalstjr47** [comment]
Hi,

As you suggested, I added a Google Drive link to the model checkpoints. Thank you!
