### ISSUE TITLE
min_mean_abs for mdx_C

### ISSUE THREAD

**Issue by KimberleyJensen** [kuielab/sdx23#6]
For mdx_AB and cdx_A you used

if np.abs(source).mean() >= self.min_mean_abs:  # remove quiet chunks
                break

But this code isn't in the mdx_C branch, please can you tell me if you found that this made the mdx_C training performance worse or if there was a reason why you didn't use it for mdx_C?

Thank you :relaxed:

**Comment by rlaalstjr47** [comment]
Hi,

Removing quiet chunks didn't effect mdx_C models. SDR difference was less than 0.01dB I think.
